### ISSUE TITLE
UI Improvement Suggestions

### ISSUE THREAD

**Issue by soundyogi** [xrchz/lidont#12]
community suggestions:
- maybe move the lidont logo to where the hamburger image is in the top left, then shift the rest of the page up
- add some description / warning before they stake. On what exactly that means
- May need to add a privacy policy / t&c, sanctions and all, fun stuff ?

**Comment by xrchz** [comment]
I don't think the policy stuff is necessary if the frontend is decentralised right?

**Comment by soundyogi** [comment]
this is just what notes I took from community suggestions. and yeah depends who runs the FE on a server I guess.
